### ISSUE TITLE
cpp_utils/BLEAdvertising ctor missing peer_addr_type for esp-idf v3.2

### ISSUE THREAD

**Issue by rkone** [nkolban/esp32-snippets#726]
I was getting errors using the BLE classes after updating to esp-idf 3.2 ("Invalid advertisting peer address type parameters").

it's solved by adding the following line in BLEAdvertising::BLEAdvertising(): 
m_advParams.peer_addr_type = BLE_ADDR_TYPE_PUBLIC;

**Comment by chegewara** [comment]
Thanks for info, looks like its been implemented as per request:
https://github.com/espressif/esp-idf/issues/2714

**Comment by chegewara** [comment]
Should be fixed in last commit.

**Comment by rkone** [comment]
I think you missed BLEScan.h from the commit. I'm missing definitions for BLEScan::getResults() and BLEScan::clearResults()

**Comment by chegewara** [comment]
@rkone Fixed, thanks.

**Comment by rkone** [comment]
Thank you for the updates! Now to figure out what else got broken migrating to 3.2...
